services:
  rabbitmq:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.rabbitmq.entrypoints=http" 
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.cloud.local`)"
      - "traefik.http.middlewares.rabbitmq-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.rabbitmq.middlewares=rabbitmq-https-redirect"
      - "traefik.http.routers.rabbitmq-secure.rule=Host(`rabbitmq.cloud.local`)"
      - "traefik.http.routers.rabbitmq-secure.entrypoints=https"
      - "traefik.http.routers.rabbitmq-secure.tls=true"
      - "traefik.http.services.rabbitmq-secure.loadbalancer.server.port=15672"

networks:
    traefik-proxy:
        external: true
    internal:
        external: true